spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@aiclass_high?TNS_ADMIN=C:/aiclass/Spring/Wallet_aiclass
    username: admin
    password: Asd5516&5070
