spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@aiclass_high?TNS_ADMIN=D:/edu/WEB/Spring/Wallet_aiclass
    username: admin
    password: James99121400
