spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@aiclass_high?TNS_ADMIN=D:/JinAirCloneCoding/Wallet_aiclass
    username: admin
    password: Asdfgh951753
