spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@aiclass_high?TNS_ADMIN=C:\study\Spring\Wallet_aiclass
    username: admin
    password: Laseunghyun7738..
